clear;
addpath '/data/gpfs/projects/punim0801/Meditation_pilot/Code/palm-alpha119';
 
%% NF Day 1
palm -i '/data/scratch/projects/punim0801/NF_Meditation/FSL_FEAT/gPPI/third-level/pcc_full_0p3/Final_group_diff/d1/cope_pcc_rem2_0p3_rest-med_d1.nii' ...
    -m '/data/scratch/projects/punim0801/NF_Meditation/FSL_FEAT/gPPI/third-level/pcc_full_0p3/Final_group_diff/d1/YeoCEN_SN_mask_thr0p3.nii' ...
    -d '/data/scratch/projects/punim0801/NF_Meditation/FSL_FEAT/gPPI/third-level/pcc_full_0p3/Final_group_diff/d1/group_diff_D1_sss_AG_rem2_design.mat'...
    -t '/data/scratch/projects/punim0801/NF_Meditation/FSL_FEAT/gPPI/third-level/pcc_full_0p3/Final_group_diff/d1/group_diff_AG_cont-exp.con'...
    -C 2.6 -save1-p -n 10000 ...
    -o '/data/scratch/projects/punim0801/NF_Meditation/FSL_FEAT/gPPI/third-level/pcc_full_0p3/Final_group_diff/d1/output/c-e_r-m_rem2'

%% NF Day 2
palm -i '/data/scratch/projects/punim0801/NF_Meditation/FSL_FEAT/gPPI/third-level/pcc_full_0p3/Final_group_diff/Input/cope_pcc_rem2_0p3_rest-med_d2.nii' ...
    -m '/data/scratch/projects/punim0801/NF_Meditation/FSL_FEAT/gPPI/third-level/pcc_full_0p3/Final_group_diff/Masks/YeoCEN_SN_mask_thr0p3.nii' ...
    -d '/data/scratch/projects/punim0801/NF_Meditation/FSL_FEAT/gPPI/third-level/pcc_full_0p3/Final_group_diff/Setting/group_diff_D2_sss_AG_rem2_design.mat'...
    -t '/data/scratch/projects/punim0801/NF_Meditation/FSL_FEAT/gPPI/third-level/pcc_full_0p3/Final_group_diff/Setting/group_diff_AG_exp-cont.con'...
    -C 2.6 -save1-p -n 10000 ...
    -o '/data/scratch/projects/punim0801/NF_Meditation/FSL_FEAT/gPPI/third-level/pcc_full_0p3/Final_group_diff/output/YeoCEN_SN_mask_0p3/e-c_r-m_rem2'


